### ISSUE TITLE
BibCode Key needs updated (API too?)

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#1625]
https://adsabs.github.io/blog/transition-reminder

**Comment by ms609** [comment]
I've just logged in to the new AdsAbs API, and it looks to me that we are using the new Bibcode key already – what have you seen that makes you think otherwise?  Is it the API end point that needs updating (to https://api.adsabs.harvard.edu/v1/search/query?q=star&fl=bibcode ?)

**Comment by GlazerMann** [comment]
I have not looked closely other than seeing that we will need to change someday

**Comment by ms609** [comment]
I thought I remembered updating this some time ago, at least when we switched to the new "call all the APIs at the start" code restructure, but maybe further revision is needed.  If you're seeing an error message or the API is returning a "change your code" message, let me know and I can take a look; otherwise I'll close this as hopefully fixed.
