### ISSUE TITLE
Proposal to watch for empty templates

### ISSUE THREAD

**Issue by ms609** [ms609/citation-bot#1785]
Per https://meta.wikimedia.org/wiki/Community_Wishlist_Survey_2019/Citations/Bring_back_doi_bot, it seems that there is appetite for the bot to automatically expand empty templates.

Road map:

- Complete Bot Request For Approval

- Edit Cite Journal template so that very incomplete templates (e.g. just a doi / pmid) are added to a maintenance category

- Periodically activate category.php  on this category, using cron.

**Comment by GlazerMann** [comment]
Closing, since it looks they will probably never get around to writing the code.   Also, they will reach out to us if there is anything we need to to.

**Comment by ms609** [comment]
I'd be quite keen to have a stab at this at some point – if I ever get the time.  I'll keep it open for now, if that's okay.

**Comment by nemobis** [comment]
I think Headbomb also regularly runs the bot on some specific patterns, such as [bare refs](https://en.wikipedia.org/w/index.php?title=Liquid_carbon_dioxide&diff=prev&oldid=905919177), so that could be in scope. It would reduce his manual work and make the bot more responsive for others (if the process can run in a separate thread which doens't consume the resources of the web tool).

**Comment by nemobis** [comment]
The command line options seem to be still available. What about testing it on a few example pages? WikipediaBot::_construct() uses "Citation_bot" as username for the edit summary if none is provided.

**Comment by GlazerMann** [comment]
I am going to close, since the bot supports command line operation on categories.  Secondly, so does the web interface.  Lastly, we could just redeploy the Dev BOT if needed to do this.   Lastly minus one, I think Headbomb already does this.  All that’s missing is a maintenance category.   Lastly minus two, we have the multiple page API, so we don’t even need that.
