### ISSUE TITLE
Replace typos

### ISSUE THREAD

**Issue by GlazerMann** [ms609/citation-bot#429]
We probably need a plan to protect us from the ever growing list of valid parameters.   See the pull that adds more

**Comment by ms609** [comment]
Probably the thing to do is to add a few loud notices to the pages and Wiki-source of relevant templates, with a link to the relevant file on GitHub, encouraging any editors to either add the parameters themselves or at least bring them to our attention.

I did once have a script that would pull the parameters from a page on Wikipedia instead of GitHub, but no-one seemed to update that list and I worried about inadvertent edits.

The alternative is to parse the source of the relevant templates and extract template names, which would be possible, but a fair bit of work...

**Comment by GlazerMann** [comment]
There is the giant whitelist, but even that is incomplete

**Comment by GlazerMann** [comment]
Probably need to add support for #### notation instead of last1, last2, etc.

**Comment by GlazerMann** [comment]
I will right code to deal with #### instead of numbers

**Comment by GlazerMann** [comment]
We probably should split the list into two.  Things we replace with and things we don’t.  For example we recognize coauthors but do not add it.

**Comment by GlazerMann** [comment]
There is the giant whitelist
https://en.m.wikipedia.org/wiki/Module:Citation/CS1/Whitelist
but even that is incomplete, since some templates as there own

I made a pull that gets rid of listing all the numbers
